services:
  # Database - To run the DHIS2 postgres database
  db:
    image: ghcr.io/baosystems/postgis:16-3.5
    # Note: If you're on Apple Silicon (M1/M2/M3), you may need to uncomment the line below
    # platform: linux/arm64
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
      - ./day-1-initial-setup/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null" ]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5

  # DHIS2 - To run the DHIS2 core web services
  web:
    image: dhis2/core:42
    volumes:
      - ./day-1-initial-setup/dhis.conf:/opt/dhis2/dhis.conf
    environment:
      - WAIT_FOR_DB_CONTAINER=db:5432 -t 0
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -S -O /dev/null http://127.0.0.1:8080/dhis-web-login/ 2>&1| grep -q 'HTTP.*200'" ]
      start_period: 120s
      interval: 10s
      timeout: 5s
      retries: 5

# PGAdmin - To inspect and manage the database
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@test.no
#      - PGADMIN_DEFAULT_PASSWORD=district
#    ports:
#      - "5050:80"
#    depends_on:
#        - db
